- name: Check if network exists
  docker_network_info:
    name: vtapp
  register: docker_network
  become: true
  
  
- name: Create network
  docker_network:
    name: vtapp
    state: present
  when: docker_network.exists == false
  become: true

- name: Copy folder files/fluentd to /etc
  copy:
    src: files/fluentd
    dest: /etc
    owner: root
    group: root
    mode: 0755
  become: true
  when: inventory_hostname == "vm3"

- name: Run fluentd docker image 
  docker_container:
    name: fluentd
    image: duongtm3102/fluentd:latest
    restart_policy: unless-stopped
    networks:
      - name: vtapp
    hostname: fluentd
    volumes:
      - /etc/fluentd:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  become: true
  when: inventory_hostname == "vm3"
  